dist: trusty
sudo: required
language: node_js

node_js:
  - "9"

install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install

script:
  - ganache-cli -e 10000000 -p 7545 -g 1
  - truffle compile
  - truffle test
