dist: trusty
sudo: required
language: node_js

node_js:
  - "9"

install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install -g coveralls
  - npm install solidity-coverage
  - npm install
  
jobs:
  fast_finish: true
  include:
    - stage: compile
      script: truffle compile
    - stage: deploy
      script: ganache-cli -e 10000000 -p 7545 -g 1 > /dev/null & truffle deploy
  allow_failures:
    - stage: test
      script: truffle test
    - stage: coverage
      script: npm run coverage && cat coverage/lcov.info | coveralls
