dist: trusty
sudo: required
language: node_js

node_js:
  - "9"

install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install -g coveralls
  - npm install solidity-coverage
  - npm install

script:
  - ganache-cli -e 10000000 -p 7545 -g 1 > /dev/null &
  - sleep 5
  - truffle compile
  - truffle test
  - npm run coverage && cat coverage/lcov.info | coveralls
